### ISSUE TITLE
Mainnet frontend checklist

### ISSUE THREAD

**Issue by osarrouy** [AragonBlack/fundraising#154]
## Generic

- [x] Frontend loading issue. The frontend sometimes takes hours to load [either the presale or the regular trading interface, either when it's a brand new DAO or an already existing one with orders]. The bad news is that it does not look deterministic so it will be a mess to debug. My first clue would be that it could be some kind of a race / coordination issue in the loading status check in the background script [the one where we check whether all the needed parameters are correctly loaded to spawn the frontend]. @xseignard 

## Presale

- [x] We should make it obvious what the current account's contribution is from a glance. We should also show contextual cliff & vesting details [for the current user]. Patty suggested that we had these details in the timeline in a dedicated row under the existing two ones. Below each step we can add the contextual details for the current user: the current amount of their contribution under the first step and a contextual message under the other one [cliff and vesting date are the same for all so it's just about wording it the right way] @xseignard @deam

- [x] We should also make clear how many shares contributors hold. Pay suggested to add a card [under the timeline] with an array of the current user contributions and the shares they bought trough it [and eventually a total of all the added contributions / returns] @deamme

**Comment by cryptodani** [comment]
[ ] Check if new DAI launched today convention is respected and supported :
- DAI ticker for MCD and SAI ticker for single collateral DAI
- If people send new DAI to our old SAI contract will be lost funds, vice versa for old SAI add support
https://blog.makerdao.com/what-to-expect-with-the-launch-of-multi-collateral-dai/
