### ISSUE TITLE
Aragon Fundraising Checklist: v2.0.0 

### ISSUE THREAD

**Issue by osarrouy** [AragonBlack/fundraising#179]
## Contracts

- [ ] Support for `approveAndCall`. See #151.
- [ ] Support artificial collateral injections. See #150.
- [ ] Support parameters interpolation for collateral token updates. See #149.
- [ ] Support a buy proxy. See #46.
